name = "fullstack-boilerplate"
main = "src/worker.ts"
compatibility_date = "2024-12-16"
compatibility_flags = ["nodejs_compat"]

[env.test]
name = "fullstack-boilerplate"

[[d1_databases]]
binding = "DB"
database_name = "fullstack-db"
database_id = "<YOUR_DATABASE_ID>"

[observability]
[observability.logs]
enabled = true
invocation_logs = true